spring:
  application:
    name: E_commerce_Application

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_application?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false #by adding this the Spring won't keeps the database connection open until the entire HTTP request finishes
  jwt:
    secret: ${JWT_SECRET}


external:
  api:
    url: ${EXTERNAL_API}


